
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Deliberately read process.env directly instead of using the `env()` helper
// from "prisma/config": that helper throws immediately when the config
// module loads if the variable is unset, which breaks `prisma generate`
// (invoked from postinstall) on platforms like Vercel that don't expose
// project environment variables during the dependency-install phase —
// generate never needs a live DB connection at all. Commands that actually
// need to connect (migrate deploy, etc.) run later, once DATABASE_URL is
// genuinely available, and will fail with a clear error then if it's not.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed/index.ts",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL ?? "",
  },
});
