
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Deliberately read process.env directly instead of using the `env()` helper
// from "prisma/config": that helper throws immediately when the config
// module loads if the variable is unset, which breaks `prisma generate`
// (invoked from postinstall) on platforms like Vercel that don't expose
// project environment variables during the dependency-install phase —
// generate never needs a live DB connection at all. Commands that actually
// need to connect (migrate deploy, etc.) run later, once DATABASE_URL is
// genuinely available, and will fail with a clear error then if it's not.
const pooledUrl = process.env.DATABASE_URL ?? "";

/**
 * Migrations must NOT run through a connection pooler.
 *
 * `prisma migrate deploy` takes a Postgres *session-level* advisory lock
 * (`SELECT pg_advisory_lock(...)`) to stop two deploys migrating at once.
 * Neon's pooled endpoint is PgBouncer in transaction mode, which hands each
 * statement to whatever backend is free rather than pinning a session — so
 * the lock can never be held, and `migrate deploy` fails every time with
 * "P1002 ... Timed out trying to acquire a postgres advisory lock". This is
 * deterministic, not a flaky-network timeout.
 *
 * Neon exposes the same database on a direct (non-pooled) endpoint at the
 * same hostname minus the `-pooler` suffix, so the direct URL is derived
 * from DATABASE_URL rather than requiring a second secret to be kept in
 * sync. `DIRECT_URL` is the repository's explicit override;
 * `DATABASE_URL_UNPOOLED` is accepted from Neon's Vercel integration, and
 * `DIRECT_DATABASE_URL` remains a temporary backwards-compatible alias.
 *
 * Only the schema engine uses this. The application keeps using the pooled
 * URL at runtime, which is what a serverless deployment wants.
 */
export function deriveDirectUrl(url: string): string {
  if (!url) return "";
  try {
    const parsed = new URL(url);
    if (!parsed.hostname.includes("-pooler")) return url;
    parsed.hostname = parsed.hostname.replace("-pooler", "");
    return parsed.toString();
  } catch {
    // Not a parseable URL — hand it back untouched and let the engine
    // report the real problem rather than masking it here.
    return url;
  }
}

/**
 * Migrations must never reach a database nobody meant to name.
 *
 * A shell can carry an ambient DATABASE_URL/DIRECT_URL — this repository has
 * been bitten twice: once by T81/T83 tests writing into a hosted database, and
 * once by `prisma migrate status` resolving to production because an inline
 * `DATABASE_URL=` was empty while an ambient DIRECT_URL was not. Both are the
 * same shape: a *partial* configuration, where the variable the operator
 * thought they set is not the one the schema engine actually used.
 *
 * So refuse the partial cases and let the fully-specified ones through:
 *   - neither set — fine, `prisma generate` never connects;
 *   - DATABASE_URL alone — fine, the direct URL is derived from it;
 *   - a direct override with no DATABASE_URL — refused.
 *
 * A direct override naming a different host than DATABASE_URL is deliberately
 * still allowed: that is this repository's documented escape hatch for a
 * separate migration endpoint, and narrowing it here would break it.
 *
 * Never echo either value; the message names variables, never their contents.
 */
export function assertConsistentMigrationTarget(env: Record<string, string | undefined>): void {
  const pooled = env.DATABASE_URL?.trim() ?? "";
  const overrideName = (["DIRECT_URL", "DATABASE_URL_UNPOOLED", "DIRECT_DATABASE_URL"] as const)
    .find((name) => (env[name] ?? "").trim());
  if (!overrideName) return;
  if (!pooled) {
    throw new Error(
      `${overrideName} is set but DATABASE_URL is empty. Set both explicitly for the database you intend to migrate — ` +
        "an ambient shell variable must never decide the target.",
    );
  }
}

export function resolveDirectUrl(env: Record<string, string | undefined>): string {
  assertConsistentMigrationTarget(env);
  return env.DIRECT_URL || env.DATABASE_URL_UNPOOLED || env.DIRECT_DATABASE_URL || deriveDirectUrl(env.DATABASE_URL ?? "");
}

const directUrl = resolveDirectUrl(process.env);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed/index.ts",
  },
  engine: "classic",
  datasource: {
    url: pooledUrl,
    directUrl,
  },
});
