import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, FileScan } from "lucide-react";
import { resolveAiActor } from "@/lib/ai";
import { isSiteInScope } from "@/lib/ai/authorization";
import { getActivityHistoryDetail, SCOPE_LABELS, STATUS_LABELS, STATUS_TONES } from "@/lib/activity-history-service";
import { DOCUMENT_KIND_LABELS, DOCUMENT_STATUS_LABELS } from "@/lib/documents-service";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { OriginBadge, ValueOrigin } from "@/components/ai/ai-disclosure";

function Row({ label, value, mono }: { label: string; value: string | null; mono?: boolean }) {
  return (
    <div className="flex flex-wrap items-baseline justify-between gap-4 border-b border-slate-100 py-2 last:border-b-0">
      <dt className="text-sm text-slate-500">{label}</dt>
      <dd className={mono ? "text-sm tabular-nums text-slate-900" : "text-sm font-medium text-slate-900"}>
        {value ?? <span className="italic text-slate-400">not recorded</span>}
      </dd>
    </div>
  );
}

/**
 * Read-only detail for one historical activity record. Everything on this
 * page comes from what was already stored when the entry was submitted and
 * calculated — nothing here is recomputed, and no report is generated by
 * viewing it.
 */
export default async function ActivityDataDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  const actor = await resolveAiActor();
  if (!actor) redirect("/login");

  const entry = await getActivityHistoryDetail(id);
  if (!entry || !isSiteInScope(actor, entry.siteId)) notFound();

  const dp = entry.activityDataPoint;

  return (
    <div className="max-w-3xl space-y-6">
      <Link href="/activity-data" className="flex w-fit items-center gap-1 text-sm text-slate-500 hover:text-slate-800">
        <ArrowLeft className="h-3.5 w-3.5" />
        Activity Data
      </Link>

      <div>
        <h1 className="text-2xl font-semibold tracking-tight text-slate-900">{dp.dataPointName}</h1>
        <p className="mt-1 text-sm text-slate-500">
          {entry.site.name} ({entry.site.entity.name}) · {new Date(entry.periodStart).toLocaleDateString("en-GB")}
          {entry.periodEnd.getTime() !== entry.periodStart.getTime() &&
            ` – ${new Date(entry.periodEnd).toLocaleDateString("en-GB")}`}
        </p>
        <div className="mt-2 flex flex-wrap items-center gap-2">
          <Badge tone="info">{SCOPE_LABELS[dp.scope]}</Badge>
          <Badge tone="neutral">{dp.category}</Badge>
          <Badge tone={STATUS_TONES[entry.status]}>{STATUS_LABELS[entry.status]}</Badge>
          <OriginBadge origin={entry.dataOrigin as ValueOrigin} />
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Activity information</CardTitle>
        </CardHeader>
        <CardContent>
          <dl>
            <Row label="Activity date" value={new Date(entry.periodStart).toLocaleDateString("en-GB")} />
            <Row
              label="Reporting period"
              value={`${new Date(entry.periodStart).toLocaleDateString("en-GB")} – ${new Date(entry.periodEnd).toLocaleDateString("en-GB")}`}
            />
            <Row label="Scope" value={SCOPE_LABELS[dp.scope]} />
            <Row label="Category" value={dp.category} />
            <Row label="Activity type" value={entry.factorOption?.label ?? null} />
            <Row label="Site" value={`${entry.site.name} (${entry.site.entity.name})`} />
            <Row label="Supplier" value={entry.supplierName} />
            <Row label="Quantity entered" value={`${entry.rawValue.toString()} ${entry.rawUnit}`} mono />
            {entry.canonicalUnit !== entry.rawUnit && (
              <Row label="Converted for calculation" value={`${entry.canonicalValue.toString()} ${entry.canonicalUnit}`} mono />
            )}
            <Row label="Notes" value={entry.notes} />
          </dl>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Emissions</CardTitle>
        </CardHeader>
        <CardContent>
          {entry.calculations.length === 0 ? (
            <p className="text-sm text-slate-500">
              No emission factor was available for this category when this entry was saved — the activity data is stored
              and will be included once a matching factor is imported.
            </p>
          ) : (
            <div className="space-y-4">
              {entry.calculations.map((c) => (
                <div key={c.id} className="rounded-lg bg-slate-50 p-3">
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <span className="text-sm font-medium text-slate-900">
                      {c.basis.replace(/_/g, " ").toLowerCase()}
                      {c.scope3Category ? ` · ${c.scope3Category}` : ""}
                    </span>
                    <span className="text-lg font-semibold tabular-nums text-slate-900">
                      {Number(c.resultKgCo2e).toLocaleString("en-GB", { maximumFractionDigits: 1 })} kgCO2e
                    </span>
                  </div>
                  <dl className="mt-2">
                    <Row label="Emission factor" value={`${c.factorValueSnapshot.toString()} kgCO2e per ${c.factorUnitSnapshot}`} mono />
                    <Row label="Factor source" value={c.factorSourceSnapshot} />
                    <Row label="Factor vintage" value={c.factorVintageSnapshot} />
                    <Row label="Factor region" value={c.emissionFactor.region} />
                    <Row label="Calculation method" value={c.formulaApplied} />
                    <Row label="Calculated" value={new Date(c.calculatedAt).toLocaleString("en-GB")} />
                    <Row label="Data quality tier" value={c.dataQualityTier} />
                  </dl>
                  <Link
                    href={`/calculations/${c.id}`}
                    className="mt-2 inline-block text-sm font-medium text-blue-700 hover:text-blue-800"
                  >
                    How this figure was calculated →
                  </Link>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {entry.sourceDocument && (
        <Card>
          <CardHeader>
            <CardTitle>Evidence</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            <Link
              href={`/documents/${entry.sourceDocument.id}`}
              className="flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2 text-sm text-slate-700 hover:bg-slate-100"
            >
              <FileScan className="h-4 w-4 text-slate-400" />
              {entry.sourceDocument.filename}
              <Badge tone="neutral">{DOCUMENT_KIND_LABELS[entry.sourceDocument.kind]}</Badge>
              <span className="text-xs text-slate-400">
                uploaded {new Date(entry.sourceDocument.uploadedAt).toLocaleDateString("en-GB")}
              </span>
            </Link>
            <p className="text-xs text-slate-400">Extraction status: {DOCUMENT_STATUS_LABELS[entry.sourceDocument.status]}</p>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Record information</CardTitle>
        </CardHeader>
        <CardContent>
          <dl>
            <Row label="Entry method" value={entry.dataOrigin.replace(/_/g, " ").toLowerCase()} />
            <Row label="Entered by" value={entry.enteredBy.name} />
            <Row label="Entered at" value={new Date(entry.enteredAt).toLocaleString("en-GB")} />
            <Row label="Last updated" value={new Date(entry.updatedAt).toLocaleString("en-GB")} />
            <Row label="Review status" value={entry.plausibilityFlagged ? (entry.plausibilityReason ?? "Flagged") : null} />
          </dl>
        </CardContent>
      </Card>
    </div>
  );
}
