import type { FrozenBoardPack } from "../../lib/board/contracts";
import { compareCarbon, coverageLabel, formatPercent, formatTonnes } from "../../lib/board/metrics";
import { BoardLink, PageHeader, StatusBadge, SyntheticDisclosure } from "./primitives";

/** Render only the saved snapshot; never refetch current records to fill an issued pack. */
export function ManagementPack({ pack }: { pack: FrozenBoardPack }) {
  const model = pack.snapshot, carbon = model.carbon.state === "ready" ? model.carbon.data : null;
  return <article className="bd-pack">{model.synthetic && <SyntheticDisclosure />}<PageHeader eyebrow={`${pack.reference} · Version ${pack.version}`} title="Environmental management review" description={`${model.organisationName} · ${model.periodLabel}`} />
    <StatusBadge tone={pack.status === "issued" ? "neutral" : "warning"}>{pack.status === "issued" ? "Issued snapshot" : "Draft — not an approved decision"}</StatusBadge><p>Prepared by {pack.preparedBy} · {pack.issuedAt ? `Issued ${pack.issuedAt}` : "Not issued"}{pack.approvedBy ? ` · Approved by ${pack.approvedBy}` : " · Approval not recorded"}</p>
    <section><h2>Performance and coverage</h2>{carbon ? <><div className="bd-pack-headline">{formatTonnes(carbon.current.kgCO2e)}<small>tCO₂e · location-based headline</small></div><p>{formatPercent(compareCarbon(carbon.current, carbon.previous).percent)} vs {model.previousPeriodLabel}. {coverageLabel(carbon.current.coverage)}.</p><p>Scope 2 market-based companion: {formatTonnes(carbon.marketBasedKg)} tCO₂e; excluded from headline addition. Scope 3: {carbon.quantifiedCategories}/15 categories quantified; {carbon.screenedCategories === null ? "screening not recorded" : `${carbon.screenedCategories}/15 screened`}.</p><table className="bd-table"><caption className="bd-sr-only">Site emissions in the issued snapshot</caption><thead><tr><th scope="col">Site</th><th scope="col">Total tCO₂e</th></tr></thead><tbody>{carbon.sites.map(s => <tr key={s.id}><th scope="row">{s.name}</th><td>{formatTonnes(s.current.kgCO2e)}</td></tr>)}</tbody></table></> : <p>Carbon section unavailable at snapshot cutoff.</p>}</section>
    <section><h2>Management attention at cutoff</h2>{model.attention.state === "ready" ? <ol>{model.attention.data.items.map(item => <li key={item.key}><strong>{item.title}</strong><p>{item.implication} Owner: {item.owner}. {item.dueDate ? `Due ${item.dueDate}.` : ""}</p></li>)}</ol> : <p>Attention section unavailable at cutoff.</p>}</section>
    <section><h2>Decisions and resources</h2>{pack.decisions.map((d, i) => <div key={i} className="bd-pack-decision"><h3>{d.title}</h3><StatusBadge tone={d.status === "draft" ? "warning" : "neutral"}>{d.status === "draft" ? "Draft decision" : "Approved decision"}</StatusBadge><p>{d.rationale}</p><p>Owner: {d.owner} · {d.dueDate ?? "No due date set"}</p></div>)}</section>
    <section className="bd-pack-sources"><h2>Evidence and source revisions</h2><p>Cutoff {model.capturedAt}. Later changes do not rewrite this snapshot. Source links require current permission and may show later workflow status; the pinned revision below remains authoritative for this pack.</p><ul>{pack.sourceRevisions.map(s => <li key={`${s.kind}:${s.id}:${s.revision}`}><BoardLink href={s.href}>{s.label}</BoardLink> · {s.kind} · {s.revision}</li>)}</ul><p className="bd-checksum">Saved payload SHA-256: <span data-testid="saved-pack-sha256">{pack.payloadSha256}</span></p></section>
  </article>;
}
